apply plugin: 'com.android.application'
apply plugin: 'jacoco'
apply plugin: 'org.jetbrains.kotlin.android'

android {
    compileSdkVersion 36
    defaultConfig {
        applicationId "io.github.freewebmovement.igniter"
        minSdkVersion 21
        targetSdkVersion 35
        versionCode 1
        versionName "0.1.4"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
            debugSymbolLevel 'FULL'
        }
        externalNativeBuild {
            cmake {
                arguments "-DANDROID_CPP_FEATURES=rtti exceptions"
                cppFlags ''
            }
        }
        ndkVersion "19.2.5345600"
//        ndkVersion "20.1.5948944"
//        ndkVersion "23.1.7779620"

        multiDexEnabled true
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            ndk.debugSymbolLevel 'FULL'
        }
        debug {
            enableUnitTestCoverage true
            enableAndroidTestCoverage true
            debuggable true
        }
    }
    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
        }
    }
    splits {
        abi {
            enable true
            reset()
            include "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
            universalApk true
        }
    }
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
    tasks.withType(Test).configureEach {
        useJUnitPlatform()
        testLogging {
            exceptionFormat "full"
            events "started", "skipped", "passed", "failed"
            showStandardStreams true
        }
    }
    testOptions {
        unitTests.returnDefaultValues = true
        unitTests.includeAndroidResources = true
    }
    namespace 'io.github.freewebmovement.igniter'
    buildFeatures {
        aidl true
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation libs.core.ktx
    implementation libs.room.runtime
    annotationProcessor libs.room.compiler

    implementation libs.material
    implementation libs.appcompat
    implementation libs.recyclerview
    implementation libs.constraintlayout

    // Never updated this to higher version before new branches
    implementation libs.core

    // Retrofit
    implementation libs.retrofit
    // Retrofit with Moshi Converter
    implementation libs.converter.scalars
    implementation libs.converter.gson

    implementation libs.snakeyaml
    implementation libs.test.core
    implementation libs.work.runtime.ktx

    testImplementation libs.junit
    testImplementation libs.runner
    testImplementation libs.robolectric

    androidTestImplementation libs.test.runner
    androidTestImplementation libs.rules
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    testImplementation(libs.junit.jupiter.api)
    testRuntimeOnly(libs.junit.jupiter.engine)
    testRuntimeOnly(libs.junit.vintage.engine)
    testRuntimeOnly(libs.junit.platform.launcher)

    implementation files('src/libs/golibs.aar')
}

